# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory (this is inside the container)
WORKDIR /usr/src/app

# Copy the Python script into the container
COPY hello.py .

# Command to run the Python script
CMD ["python", "./hello.py"]
